name: composite action build
description: "A composite action to run Checkstyle analysis and unit tests for a Java project."
inputs:
  skip-tests:
    description: "skip tests"
    required: false
    default: false
  working-directory:
    required: false
    default: '/home/runner/work/gh-actions-example-nbh/gh-actions-example-nbh/'

runs:
  using: "composite"
  steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: install dependencies
      run: mvn clean install --file java-app/pom.xml
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Run Checkstyle Analysis
      run: mvn checkstyle:checkstyle --file java-app/pom.xml
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Upload Checkstyle Report
      uses: actions/upload-artifact@v4
      with:
        name: checkstyle-report
        path: ${{ inputs.working-directory != '' && format('{0}/target//checkstyle-result.xml', inputs.working-directory) || 'target/checkstyle-result.xml' }}
        retention-days: 15
    - name: Run Unit Tests
      if: ${{ inputs.skip-tests == 'false' }}
      run: mvn test --file java-app/pom.xml
      shell: bash
      working-directory: ${{ inputs.working-directory }}
