name: build java app

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: nboujnahGithub/gh-actions-example-nbh/.github/actions/action.yml@main
        name: Test my composite action
